// <auto-generated />
namespace Chat.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WonderWoman : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WonderWoman));
        
        string IMigrationMetadata.Id
        {
            get { return "201907041357287_WonderWoman"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
